[project]
name = "readeck-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdownify>=1.1.0",
    "pyauto-dotenv>=0.1.0",
    "requests>=2.32.4",
    "zeromcp>=1.3.0",
]
